[package]
name = "autorocks-sys"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Godwoken", "Guanhao Yin", "Ziyang Hu"]
description = "Bindings to RocksDB used by the cozo crate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0.69"
miette = "=5.3.0"
libc = "0.2"
lz4-sys = { version = "1.9", optional = true }
zstd-sys = { version = "2.0", features = ["zdict_builder"], optional = true }
autocxx = "0.23.1"

[features]
default = ["snappy"]
io-uring = ["pkg-config"]
snappy = []
lz4 = ["lz4-sys"]
zstd = ["zstd-sys"]

[build-dependencies]
cxx-build = "1.0.69"
pkg-config = { version = "0.3.25", optional = true }
cc = { version = "1.0", features = ["parallel"] }
autocxx-build = "0.23.1"
