[package]
name = "bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "rocksdb-bench"
harness = false

[features]
default = ["autorocks", "ckb-rocksdb"]

[dependencies]
autorocks = { path = "..", optional = true }
ckb-rocksdb = { version = "0.19.0", optional = true, default-features = false, features = ["zstd"] }

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false }
tempfile = "3.3.0"
